-- Seed initial plant catalog
INSERT INTO plants (id, name_ko, name_en, name_scientific, category, difficulty, description, environment, growth, stress_factors, rewards) VALUES
('basil',       '바질',       'Basil',          'Ocimum basilicum',     'herb',      'easy',   '향긋한 잎이 매력적인 허브.',           '{"light":"high","water":"medium","temperature":[18,30],"humidity":"medium"}', '{"days_to_mature":40,"max_height_cm":60}', '{"heat":"low","cold":"high"}',     '{"xp":50,"coins":20}'),
('rosemary',    '로즈마리',   'Rosemary',       'Salvia rosmarinus',    'herb',      'medium', '지중해 출신 향신료 허브.',             '{"light":"high","water":"low","temperature":[15,28],"humidity":"low"}',       '{"days_to_mature":80,"max_height_cm":120}','{"overwater":"high"}',             '{"xp":80,"coins":40}'),
('mint',        '민트',       'Mint',           'Mentha',               'herb',      'easy',   '시원한 향이 나는 허브.',               '{"light":"medium","water":"high","temperature":[15,28],"humidity":"high"}',   '{"days_to_mature":50,"max_height_cm":80}', '{"drought":"high"}',               '{"xp":50,"coins":20}'),
('echeveria',   '에케베리아', 'Echeveria',      'Echeveria elegans',    'succulent', 'easy',   '장미 모양의 다육식물.',                '{"light":"high","water":"low","temperature":[10,30],"humidity":"low"}',       '{"days_to_mature":120,"max_height_cm":15}','{"overwater":"high"}',             '{"xp":60,"coins":30}'),
('haworthia',   '하월시아',   'Haworthia',      'Haworthia cooperi',    'succulent', 'easy',   '반투명 잎이 특징인 다육식물.',         '{"light":"medium","water":"low","temperature":[10,28],"humidity":"low"}',     '{"days_to_mature":150,"max_height_cm":10}','{"overwater":"high"}',             '{"xp":60,"coins":30}'),
('monstera',    '몬스테라',   'Monstera',       'Monstera deliciosa',   'foliage',   'medium', '구멍 뚫린 잎이 인기인 관엽식물.',      '{"light":"medium","water":"medium","temperature":[18,30],"humidity":"high"}', '{"days_to_mature":200,"max_height_cm":300}','{"cold":"high"}',                  '{"xp":120,"coins":60}'),
('pothos',      '스킨답서스', 'Pothos',         'Epipremnum aureum',    'foliage',   'easy',   '키우기 쉬운 덩굴 관엽식물.',           '{"light":"low","water":"medium","temperature":[15,30],"humidity":"medium"}',  '{"days_to_mature":120,"max_height_cm":200}','{"cold":"medium"}',                '{"xp":40,"coins":15}'),
('marigold',    '메리골드',   'Marigold',       'Tagetes',              'flowering', 'easy',   '주황빛 꽃이 화사한 한해살이.',         '{"light":"high","water":"medium","temperature":[15,30],"humidity":"medium"}', '{"days_to_mature":60,"max_height_cm":50}', '{"frost":"high"}',                 '{"xp":70,"coins":30}'),
('orchid',      '호접란',     'Phalaenopsis',   'Phalaenopsis',         'flowering', 'hard',   '우아한 꽃이 오래 가는 난과 식물.',     '{"light":"medium","water":"low","temperature":[18,28],"humidity":"high"}',    '{"days_to_mature":300,"max_height_cm":70}','{"overwater":"high","cold":"high"}','{"xp":200,"coins":120}'),
('cherry_tomato','방울토마토','Cherry Tomato', 'Solanum lycopersicum', 'vegetable', 'medium', '달콤한 방울토마토 품종.',              '{"light":"high","water":"high","temperature":[18,30],"humidity":"medium"}',   '{"days_to_mature":75,"max_height_cm":150}','{"frost":"high","drought":"high"}','{"xp":100,"coins":80}');
